# Your discord bot token
token: ""

# The channel ID you want to the bot to post messages in
channel_id: ""

# The message the user receives when you warn him.
warn_message: "&f[&bNCPFlags&f] You have been warned."

# The message the user receives when you kick him.
kick_message: "&f[&bNCPFlags&f] You have been kicked."